### ISSUE TITLE
User login with two roles

### ISSUE THREAD

**Issue by ancgate** [rcosnita/eCommerce-RBAC#3]
Hi rcosnita,

You project is very interesting. I do have question. When it comes to a user connecting with Customer Service and Customer Service Supervisor, is he connecting with both roles containing all permission? or only with one role which he will choose after login? 

Thanks

**Comment by rcosnita** [comment]
A user will always login with his roles. For instance, if a user is included in Customer Service and Customer Service Supervisor roles he will have a union of permissions.

If you want to achieve something like roles escalation (e.g sudo like behavior) you can start a session as a regular user (e.g Customer Service user). Once you have the session active you can add additional roles to it through SessionRoles entity (https://raw.githubusercontent.com/rcosnita/eCommerce-RBAC/master/docs/wiki/rbac-erd.png).

In order to manually add roles to a session you will probably need a backend service which does this on demand.

Will this work for you?

**Comment by ancgate** [comment]
Yes, this will work. Thanks
